// Generated by CoffeeScript 1.12.7
(function() {
  var Editor;

  module.exports = Editor = (function() {
    function Editor(loader) {
      var $editorBox, editorWidthPercentage;
      this.loader = loader;
      editorWidthPercentage = 30;
      $editorBox = $($.parseHTML('<div class="column"></div>'));
      $editorBox.width(editorWidthPercentage + '%');
      $('#net-column').width((100 - editorWidthPercentage) + '%');
      $('#master-container').prepend($editorBox);
      this.editor = CodeMirror($editorBox[0], {
        value: '# Enter your network definition here.\n# Use Shift+Enter to update the visualization.',
        lineNumbers: true,
        lineWrapping: true
      });
      this.editor.on('keydown', (function(_this) {
        return function(cm, e) {
          return _this.onKeyDown(e);
        };
      })(this));
    }

    Editor.prototype.onKeyDown = function(e) {
      if (e.shiftKey && e.keyCode === 13) {
        e.preventDefault();
        return this.loader(this.editor.getValue());
      }
    };

    return Editor;

  })();

}).call(this);
