// Generated by CoffeeScript 1.12.7
(function() {
  var AppController, CaffeNetwork, Loader, showDocumentation,
    slice = [].slice;

  AppController = require('./app.coffee');

  CaffeNetwork = require('./caffe/caffe.coffee');

  Loader = require('./loader.coffee');

  showDocumentation = function() {
    return window.location.href = 'quickstart.html';
  };

  $(document).ready(function() {
    var app, loader, makeLoader, router, routes;
    app = new AppController();
    loader = new Loader(CaffeNetwork);
    makeLoader = function(loadingFunc) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return app.startLoading.apply(app, [loadingFunc].concat(slice.call(args)));
      };
    };
    routes = {
      '/gist/:gistID': makeLoader(loader.fromGist),
      '/url/(.+)': makeLoader(loader.fromURL),
      '/preset/:name': makeLoader(loader.fromPreset),
      '/editor(/?)': (function(_this) {
        return function() {
          return app.showEditor(loader);
        };
      })(this),
      '/doc': (function(_this) {
        return function() {
          return showDocumentation();
        };
      })(this)
    };
    router = Router(routes);
    return router.init('/doc');
  });

}).call(this);
