// Generated by CoffeeScript 1.12.7
(function() {
  var Notifier;

  module.exports = Notifier = (function() {
    function Notifier() {}

    Notifier._errorHandlers = [];

    Notifier._warningHandlers = [];

    Notifier.onerror = function(handler) {
      return Notifier._errorHandlers.push(handler);
    };

    Notifier.onwarning = function(handler) {
      return Notifier._warningHandlers.push(handler);
    };

    Notifier.error = function(object) {
      var handler, i, len, ref, results;
      console.log('Error: ' + object);
      ref = Notifier._errorHandlers;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        handler = ref[i];
        results.push(handler(object));
      }
      return results;
    };

    Notifier.warning = function(object) {
      var handler, i, len, ref, results;
      console.log('Warning: ' + object);
      ref = Notifier._warningHandlers;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        handler = ref[i];
        results.push(handler(object));
      }
      return results;
    };

    return Notifier;

  })();

}).call(this);
