// Generated by CoffeeScript 1.12.7
(function() {
  var toTitleCaseSaveSpaces, typeIsArray;

  exports.typeIsArray = typeIsArray = function(value) {
    return value && typeof value === 'object' && value instanceof Array && typeof value.length === 'number' && typeof value.splice === 'function' && !(value.propertyIsEnumerable('length'));
  };

  exports.asArray = function(valueOrArray) {
    if (typeIsArray(valueOrArray)) {
      return valueOrArray;
    }
    return [valueOrArray];
  };

  exports.asScalar = function(valueOrArray) {
    if (!typeIsArray(valueOrArray)) {
      return valueOrArray;
    }
    if (valueOrArray.length === 1) {
      return valueOrArray[0];
    }
    return valueOrArray;
  };

  exports.toTitleCaseSaveSpaces = toTitleCaseSaveSpaces = function(str) {
    return str[0].toUpperCase() + str.slice(1, +(str.length - 1) + 1 || 9e9).toLowerCase();
  };

  exports.toTitleCase = function(str) {
    var i, len, part, partialNames, result;
    partialNames = str.split(/[\ _]/);
    result = '';
    for (i = 0, len = partialNames.length; i < len; i++) {
      part = partialNames[i];
      result += toTitleCaseSaveSpaces(part);
    }
    return result;
  };

}).call(this);
